services:
  dns:
    build: ./dns
    container_name: dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/named.conf.local:/etc/bind/named.conf.local
      - ./dns/db.asa.br:/etc/bind/db.asa.br
    networks:
      rede:
        ipv4_address: 172.20.0.2

  proxy:
    build: ./proxy
    container_name: proxy-server
    ports:
      - "443:443"
    networks:
      rede:
        ipv4_address: 172.20.0.10

  web1:
    build: ./web1
    container_name: web1
    networks:
      rede:
        ipv4_address: 172.20.0.11

  web2:
    build: ./web2
    container_name: web2
    networks:
      rede:
        ipv4_address: 172.20.0.12
        
networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
